#!/usr/bin/env python3
"""
Generate SQL seed statements for curriculum_units and curriculum_lessons
from lesson_map JSON.

Expected JSON shape:
{
  "meta": {...},
  "units": [
    {
      "year_group": 7,
      "subject": "maths",
      "exam_board": "aqa" | null,
      "course": "gcse",
      "unit_title": "Algebra",
      "unit_order": 1,
      "lessons": ["Lesson A", "Lesson B", ...]
    },
    ...
  ]
}
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def q(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value).replace("'", "''")
    return f"'{s}'"


def normalize_text(value: Any) -> str:
    if value is None:
        return ""
    return str(value).strip()


def build_sql(payload: dict[str, Any]) -> str:
    units = payload.get("units", [])
    if not isinstance(units, list):
        raise ValueError("JSON must contain a top-level 'units' array.")

    lines: list[str] = []
    lines.append("-- Generated by supabase/seeds/seed_units_lessons.py")
    lines.append("begin;")
    lines.append("")

    for idx, unit in enumerate(units, start=1):
        if not isinstance(unit, dict):
            raise ValueError(f"Unit #{idx} is not an object.")

        year_group = unit.get("year_group")
        subject = normalize_text(unit.get("subject", "")).lower()
        exam_board_raw = unit.get("exam_board")
        exam_board = normalize_text(exam_board_raw).lower() if exam_board_raw not in (None, "") else None
        course = normalize_text(unit.get("course", "")) or "general"
        unit_title = normalize_text(unit.get("unit_title", ""))
        unit_order = unit.get("unit_order", idx)
        lessons = unit.get("lessons", [])

        if not isinstance(year_group, int):
            raise ValueError(f"Unit #{idx}: year_group must be int.")
        if not subject:
            raise ValueError(f"Unit #{idx}: subject is required.")
        if not course:
            raise ValueError(f"Unit #{idx}: course is required.")
        if not unit_title:
            raise ValueError(f"Unit #{idx}: unit_title is required.")
        if not isinstance(unit_order, int):
            raise ValueError(f"Unit #{idx}: unit_order must be int.")
        if not isinstance(lessons, list):
            raise ValueError(f"Unit #{idx}: lessons must be an array.")

        where_exam_board = "exam_board is null" if exam_board is None else f"exam_board = {q(exam_board)}"

        lines.append(f"-- Unit {idx}: {subject} Y{year_group} / {unit_title}")
        lines.append(
            "insert into public.curriculum_units (year_group, subject, exam_board, course, unit_title, unit_order)\n"
            f"values ({q(year_group)}, {q(subject)}, {q(exam_board)}, {q(course)}, {q(unit_title)}, {q(unit_order)})\n"
            "on conflict (year_group, subject, exam_board, course, unit_title)\n"
            "do update set unit_order = excluded.unit_order;"
        )
        lines.append(
            "with unit_row as (\n"
            "  select id\n"
            "  from public.curriculum_units\n"
            f"  where year_group = {q(year_group)}\n"
            f"    and subject = {q(subject)}\n"
            f"    and {where_exam_board}\n"
            f"    and course = {q(course)}\n"
            f"    and unit_title = {q(unit_title)}\n"
            "  limit 1\n"
            ")\n"
            "insert into public.curriculum_lessons (unit_id, lesson_title, lesson_order)\n"
            "select unit_row.id, v.lesson_title, v.lesson_order\n"
            "from unit_row\n"
            "join (\n"
            "  values"
        )

        lesson_values: list[str] = []
        for lesson_i, lesson in enumerate(lessons, start=1):
            lesson_title = normalize_text(lesson)
            if not lesson_title:
                continue
            lesson_values.append(f"    ({q(lesson_title)}, {q(lesson_i)})")

        if lesson_values:
            lines.append(",\n".join(lesson_values))
        else:
            lines.append("    ('(No lesson title provided)', 1)")

        lines.append(
            ") as v(lesson_title, lesson_order) on true\n"
            "on conflict (unit_id, lesson_order)\n"
            "do update set lesson_title = excluded.lesson_title;"
        )
        lines.append("")

    lines.append("commit;")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SQL seed for curriculum_units/curriculum_lessons.")
    parser.add_argument("input_json", type=Path, help="Path to lesson_map_seed_all_years_v1.json")
    parser.add_argument(
        "--output-sql",
        type=Path,
        default=Path("supabase/migrations/0005_curriculum_units_lessons_seed.sql"),
        help="Output SQL path",
    )
    args = parser.parse_args()

    payload = json.loads(args.input_json.read_text(encoding="utf-8"))
    sql = build_sql(payload)

    args.output_sql.parent.mkdir(parents=True, exist_ok=True)
    args.output_sql.write_text(sql, encoding="utf-8")
    print(f"Wrote SQL seed: {args.output_sql}")


if __name__ == "__main__":
    main()
